### PR TITLE
adding templates for issues and pull requests

### PR DESCRIPTION
**Pull request by SteveCButler**
## Description
Add issue_template.md

## Related Issue
none

## Motivation and Context
So the team has the templates handy

## How Can This Be Tested?
Check the content

## Types of changes
Adding template files, no code.

### CODE REVIEW

**Review by ahammer1 — COMMENTED** [review]
looks good!

**Review by beileibud — COMMENTED** [review]
looks good

**Review by beileibud — COMMENTED** [review]
one more to test

**Review by beileibud — APPROVED** [review]
sorry shoud click approved

**Review by ahammer1 — APPROVED** [review]
2nd approve

**Pull request merged**
